# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lop_ma_khoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giangvien',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='giangvien',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='khoa',
            name='created',
        ),
        migrations.RemoveField(
            model_name='khoa',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='khoahoc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='khoahoc',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='lop',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lop',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='monhoc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='monhoc',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='updated_by',
        ),
    ]
