# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171027_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
